project:
  type: website

website:
  title: "Garrett's Webpage"
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/garrettrmooney
      - icon: twitter
        href: https://www.twitter.com/garrettrmooney
      - icon: github
        href: https://www.github.com/garrettmooney
  twitter-card:
    creator: "@garrettrmooney"
    site: "@garrettrmooney"
    card-style: summary_large_image
  description: "Garrett Mooney's Webpage"
  repo-url: https://github.com/garrettmooney/notes
  repo-actions: [edit]
  repo-branch: main
  navbar:
    title: false
    background: dark
    pinned: false
    collapsed: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: notes/index.qmd
        text: Notes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



